use_frameworks!

platform :ios, '9.0'

target 'LCSNetworking_Example' do
  pod 'LCSNetworking', :path => '../'

  target 'LCSNetworking_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
